#!/usr/bin/env python3
"""
يولّد lib/firebase_options.dart من android/app/google-services.json
حتى لا يحتاج المستخدم سوى سر واحد (GOOGLE_SERVICES_JSON).
"""
import json
import sys
from pathlib import Path

JSON_PATH = Path("android/app/google-services.json")
OUT_PATH = Path("lib/firebase_options.dart")


def main():
    if not JSON_PATH.exists():
        print(f"لا يوجد {JSON_PATH} — تخطي التوليد")
        return 0

    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    info = data.get("project_info", {})
    clients = data.get("client", [])
    if not clients:
        print("google-services.json لا يحتوي client — تخطي")
        return 1

    client = clients[0]
    client_info = client.get("client_info", {})
    api_keys = client.get("api_key", [{}])
    api_key = api_keys[0].get("current_key", "MISSING") if api_keys else "MISSING"

    project_id = info.get("project_id", "MISSING")
    project_number = info.get("project_number", "MISSING")
    storage_bucket = info.get("storage_bucket", f"{project_id}.appspot.com")
    app_id = client_info.get("mobilesdk_app_id", "MISSING")
    package_name = client_info.get("android_client_info", {}).get(
        "package_name", "com.cady.cadysalesapp"
    )

    if project_id in ("YOUR_PROJECT_ID", "MISSING") or "YOUR_" in api_key:
        print("القيم ما زالت PLACEHOLDER — لن يُكتب firebase_options.dart")
        return 0

    content = f'''// File generated by scripts/generate_firebase_options.py from google-services.json
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    authDomain: '{project_id}.firebaseapp.com',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: '{package_name}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: '{package_name}',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );
}}
'''
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"✅ تم توليد {OUT_PATH} من google-services.json")
    print(f"   projectId={project_id}  appId={app_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
