#!/usr/bin/env python3
"""
يولّد lib/firebase_options.dart من android/app/google-services.json
حتى يكفي سر واحد: GOOGLE_SERVICES_JSON
"""
import json
import sys
from pathlib import Path

JSON_PATH = Path("android/app/google-services.json")
OUT_PATH = Path("lib/firebase_options.dart")


def main() -> int:
    if not JSON_PATH.exists():
        print(f"❌ لا يوجد {JSON_PATH}")
        return 1

    try:
        data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"❌ فشل قراءة JSON: {e}")
        return 1

    info = data.get("project_info") or {}
    clients = data.get("client") or []
    if not clients:
        print("❌ google-services.json بدون client")
        return 1

    client = clients[0]
    client_info = client.get("client_info") or {}
    api_keys = client.get("api_key") or [{}]
    api_key = (api_keys[0] or {}).get("current_key") or "MISSING"

    project_id = info.get("project_id") or "MISSING"
    project_number = str(info.get("project_number") or "MISSING")
    storage_bucket = info.get("storage_bucket") or f"{project_id}.appspot.com"
    app_id = client_info.get("mobilesdk_app_id") or "MISSING"
    package_name = (client_info.get("android_client_info") or {}).get(
        "package_name", "com.cady.cadysalesapp"
    )

    if project_id in ("YOUR_PROJECT_ID", "MISSING") or api_key.startswith("YOUR_"):
        print(f"❌ قيم وهمية: project_id={project_id!r} api_key={api_key[:12]!r}...")
        return 1

    content = f'''// Generated by scripts/generate_firebase_options.py — لا تعدّل يدوياً
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    authDomain: '{project_id}.firebaseapp.com',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: '{package_name}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
    iosBundleId: '{package_name}',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{storage_bucket}',
  );
}}
'''
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"✅ وُلّد {OUT_PATH}")
    print(f"   projectId={project_id}")
    print(f"   appId={app_id}")
    print(f"   apiKey={api_key[:8]}…")
    return 0


if __name__ == "__main__":
    sys.exit(main())
